baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
	sidebartitle = "{teopeurt}"
	sidebartagline = "digital.security, hacking, ux, product"
	GoogleAnalyticsUserID = "XXDDXX"
	categories = "life"

[[menu.main]]
    name = "About"
    url = "/about"


[[menu.social]]
  	pre = "<i class='fa fa-twitter'></i>"
      url = "http://www.twitter.com/teopeurt"
      identifier = "twitter"

[[menu.footer]]
    name = "Blog"
      url = "/posts"
