baseurl = "http://blog.teopeurt.com/"
languageCode = "en-us"
title = "My Thoughts"

[params]
	sidebartitle = "{teopeurt}"
	sidebartagline = "digital.security, mobile, api, hacking, ux, product"
	categories = "life"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
		name = "Talks"
		url = "/talks"

[[menu.main]]
		name = "Projects"
		url = "/projects"

[[menu.main]]
		name = "Blog"
		url = "/post"


[[menu.social]]
  	pre = "<i class='fa fa-twitter'></i>"
      url = "http://www.twitter.com/teopeurt"
      identifier = "twitter"

[[menu.social]]
	  	pre = "<i class='fa fa-github'></i>"
	      url = "https://github.com/teopeurt"
	      identifier = "github"

[[menu.footer]]
    name = "Blog"
      url = "/posts"
