baseurl = "http://blog.teopeurt.com/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
	sidebartitle = "{teopeurt}"
	sidebartagline = "digital.security, hacking, ux, product"
	categories = "life"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
		name = "Talks"
		url = "/talks"

[[menu.main]]
		name = "Projects"
		url = "/projects"

[[menu.main]]
		name = "Blog"
		url = "/post"


[[menu.social]]
  	pre = "<i class='fa fa-twitter'></i>"
      url = "http://www.twitter.com/teopeurt"
      identifier = "twitter"

[[menu.footer]]
    name = "Blog"
      url = "/posts"
